/**
 * Qursor++ - Multi-Framework Component Generator
 * 
 * Synthesizes production-ready reusable UI components from extracted DOM telemetry.
 * Supports React JSX, Vue 3 SFC, Angular Component, Tailwind CSS, Vanilla HTML/CSS/JS.
 */

import { mapStylesToTailwind } from './tailwind_mapper.js';

export const FRAMEWORKS = {
  REACT: 'react',
  VUE: 'vue',
  ANGULAR: 'angular',
  TAILWIND: 'tailwind',
  VANILLA: 'vanilla',
  HTML: 'html',
  CSS: 'css'
};

/**
 * Main component generator dispatch function
 * @param {Object} data Element inspection payload
 * @param {string} framework Target framework key
 * @returns {string} Formatted code snippet
 */
export function generateComponentCode(data, framework = FRAMEWORKS.REACT) {
  if (!data) return '';

  const rawHtml = data.general ? data.general.fullOuterHTML : (data.outerHTML || '');
  const tag = (data.tag || 'DIV').toLowerCase();
  const componentName = sanitizeComponentName(data.general ? data.general.id : null, data.classes, tag);
  const styles = data.styles || {};
  const rawCss = data.rawCss || '';
  const tailwindClasses = mapStylesToTailwind(styles, tag);

  switch (framework.toLowerCase()) {
    case FRAMEWORKS.REACT:
      return generateReactJSX(rawHtml, componentName, rawCss);
    case FRAMEWORKS.VUE:
      return generateVueSFC(rawHtml, componentName, rawCss);
    case FRAMEWORKS.ANGULAR:
      return generateAngularComponent(rawHtml, componentName, rawCss);
    case FRAMEWORKS.TAILWIND:
      return generateTailwindHTML(rawHtml, tailwindClasses);
    case FRAMEWORKS.VANILLA:
      return generateVanillaComponent(rawHtml, componentName, rawCss);
    case FRAMEWORKS.HTML:
      return cleanHtmlSnippet(rawHtml);
    case FRAMEWORKS.CSS:
      return rawCss || '/* No computed styles available */';
    default:
      return generateReactJSX(rawHtml, componentName, rawCss);
  }
}

/**
 * Sanitizes component name to PascalCase
 */
function sanitizeComponentName(id, classes, tag) {
  let name = 'SelectedComponent';
  if (id && id !== 'N/A') {
    name = toPascalCase(id);
  } else if (classes && classes.length > 0) {
    name = toPascalCase(classes[0]);
  } else if (tag) {
    name = toPascalCase(tag) + 'Component';
  }
  return name.replace(/[^a-zA-Z0-9]/g, '');
}

function toPascalCase(str) {
  if (!str) return 'Component';
  return str
    .replace(/[-_]/g, ' ')
    .replace(/(?:^|\s)\w/g, match => match.toUpperCase())
    .replace(/\s+/g, '');
}

/**
 * Generates clean React JSX Functional Component
 */
function generateReactJSX(html, componentName, rawCss) {
  // Convert HTML attributes to JSX syntax (class -> className, for -> htmlFor)
  let jsxHtml = html
    .replace(/\bclass=/g, 'className=')
    .replace(/\bfor=/g, 'htmlFor=')
    .replace(/\btabindex=/g, 'tabIndex=')
    .replace(/\bautocomplete=/g, 'autoComplete=')
    .replace(/\breadonly=/g, 'readOnly=')
    .replace(/\bcontenteditable=/g, 'contentEditable=')
    .replace(/\bmaxlength=/g, 'maxLength=');

  // Ensure self-closing tags for void elements in JSX
  jsxHtml = jsxHtml.replace(/<(img|input|br|hr|meta|link)([^>]*)(?<!\/)>/gi, '<$1$2 />');

  return `import React from 'react';

/**
 * ${componentName} Component
 * Generated by Qursor++ AI Inspector
 */
export default function ${componentName}({ className = '', ...props }) {
  return (
    ${indentCode(jsxHtml, 4)}
  );
}

/* Scoped Component Styles */
/*
.${componentName.toLowerCase()} {
${indentCode(rawCss, 2)}
}
*/`;
}

/**
 * Generates Vue 3 Single File Component (SFC)
 */
function generateVueSFC(html, componentName, rawCss) {
  return `<template>
${indentCode(html, 2)}
</template>

<script setup>
// Component: ${componentName}
// Generated by Qursor++ AI Inspector
defineProps({
  customClass: {
    type: String,
    default: ''
  }
});
</script>

<style scoped>
${rawCss || '/* Scoped component styles */'}
</style>`;
}

/**
 * Generates Angular 17+ Standalone Component
 */
function generateAngularComponent(html, componentName, rawCss) {
  const selector = 'app-' + componentName.toLowerCase();
  return `import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: '${selector}',
  standalone: true,
  imports: [CommonModule],
  template: \`
${indentCode(html, 4)}
  \`,
  styles: [\`
${indentCode(rawCss, 4)}
  \`]
})
export class ${componentName}Component {
  // Generated by Qursor++ AI Inspector
}`;
}

/**
 * Generates Tailwind CSS HTML
 */
function generateTailwindHTML(html, tailwindClasses) {
  if (!tailwindClasses) return html;

  // Inject or combine class attribute on top-level tag
  if (/\bclass="/.test(html)) {
    return html.replace(/\bclass="([^"]*)"/, (match, existing) => {
      const combined = (existing + ' ' + tailwindClasses).trim();
      return `class="${combined}"`;
    });
  } else {
    return html.replace(/^<([a-zA-Z0-9-]+)/, `<$1 class="${tailwindClasses}"`);
  }
}

/**
 * Generates Vanilla HTML / CSS / JS bundle
 */
function generateVanillaComponent(html, componentName, rawCss) {
  const className = componentName.toLowerCase() + '-wrapper';
  return `<!-- ${componentName} HTML Structure -->
<div class="${className}">
${indentCode(html, 2)}
</div>

<style>
/* ${componentName} Styles */
.${className} {
${indentCode(rawCss, 2)}
}
</style>

<script>
// ${componentName} Interactive Logic
document.addEventListener('DOMContentLoaded', () => {
  const container = document.querySelector('.${className}');
  if (container) {
    console.log('[${componentName}] Initialized.');
  }
});
</script>`;
}

/**
 * Formats clean semantic HTML
 */
function cleanHtmlSnippet(html) {
  if (!html) return '';
  return html.trim();
}

function indentCode(str, spaces = 2) {
  if (!str) return '';
  const pad = ' '.repeat(spaces);
  return str
    .split('\n')
    .map(line => (line.trim() ? pad + line : ''))
    .join('\n');
}
